[build]
    command   = "npm run export"
    publish   = "out"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[functions]
    node_bundler = "esbuild"

[context.production.environment]
    NEXT_SERVERLESS = "true"
    NODE_ENV = "production"